pyvhost/apache_config/urls.py
from django.urls import path

from .views.index import index
from .views.create import create
from .views.list import listing
from .views.delete import delete
from .views.show import show

app_name = 'apache_config'

urlpatterns = [
    path('', index, name='index'),
    path('list/', listing, name='listing'),
    path('create/', create, name='create'),
    path('show/<int:vhost_id>/', show, name='show'),
    path('delete/<int:vhost_id>/', delete, name='delete')
]

pyvhost/pyvhost/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apache_config.urls', namespace='apache_config')),
]

pyvhost/apache_config/models.py
from django.db import models


class VirtualHost(models.Model):

    def __str__(self):
        return self.domain_name

    domain_name = models.CharField(max_length=100)
    include_www = models.BooleanField(default=True)
    redirect_https = models.BooleanField(default=False)
    lets_encrypt = models.BooleanField(default=False)
    active = models.BooleanField(default=False)

    ssl_cert = models.TextField(blank=True)
    ssl_key = models.TextField(blank=True)
    ssl_bundle = models.TextField(blank=True)

pyvhost/apache_config/forms.py
from django.forms import ModelForm, Form, fields
from .models import VirtualHost


class VirtualHostForm(ModelForm):
    class Meta:
        model = VirtualHost
        fields = '__all__'


class DeleteConfirmation(Form):
    confirm = fields.BooleanField(label="Are you sure?")

pyvhost/apache_config/views/create.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from ..models import VirtualHost
from ..forms import VirtualHostForm
from ..config_functions.apache_vhost import write_vhost


def create(request):
    create_form = VirtualHostForm(request.POST or None)

    if request.method == 'POST' and create_form.is_valid():
        new_vhost = VirtualHost(
            domain_name=create_form.cleaned_data['domain_name'],
            include_www=create_form.cleaned_data['include_www'],
            redirect_https=create_form.cleaned_data['redirect_https'],
            lets_encrypt=create_form.cleaned_data['lets_encrypt'],
            active=create_form.cleaned_data['active'],
            ssl_cert=create_form.cleaned_data['ssl_cert'],
            ssl_key=create_form.cleaned_data['ssl_key'],
            ssl_bundle=create_form.cleaned_data['ssl_bundle']
        )
        new_vhost.save()
        
        if new_vhost.active:
            write_vhost(new_vhost)

        return HttpResponseRedirect(
            reverse('apache_config:show', kwargs={
                'vhost_id': new_vhost.id
            })
        )

    return render(
        request,
        'apache_config/create.html',
        {'create_form': create_form}
    )

pyvhost/apache_config/views/delete.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from ..models import VirtualHost
from ..forms import DeleteConfirmation
from ..config_functions.apache_vhost import delete_vhost


def delete(request, vhost_id):
    vhost = get_object_or_404(VirtualHost, pk=vhost_id)
    confirm_delete = DeleteConfirmation(request.POST or None)

    if request.method == 'POST' and confirm_delete.is_valid():
        delete_vhost(vhost)

        if confirm_delete.cleaned_data['confirm']:
            vhost.delete()
            return HttpResponseRedirect(
                reverse('apache_config:listing')
            )

    return render(
        request,
        'apache_config/delete.html',
        {
            'vhost': vhost,
            'confirm_delete': confirm_delete
        }
    )

pyvhost/apache_config/views/index.py
from django.shortcuts import reverse
from django.http import HttpResponseRedirect


def index(request):
    return HttpResponseRedirect(
        reverse('apache_config:listing')
    )

pyvhost/apache_config/views/list.py
from django.shortcuts import render, reverse
from ..models import VirtualHost


def listing(request):
    vhost_list = VirtualHost.objects.all()
    create_url = reverse('apache_config:create')
    return render(
        request,
        'apache_config/list.html',
        {'vhost_list': vhost_list, 'create_url': create_url}
    )

pyvhost/apache_config/views/show.py
from django.shortcuts import render, get_object_or_404, resolve_url
from ..models import VirtualHost
from ..config_functions import apache_vhost


def show(request, vhost_id):
    vhost = get_object_or_404(VirtualHost, pk=vhost_id)
    delete_url = resolve_url('apache_config:delete', vhost_id=vhost.id)
    listing_url = resolve_url('apache_config:listing')
    rendered_vhost = apache_vhost.gen_vhost(vhost)

    return render(
        request,
        'apache_config/show.html',
        {
            'vhost': vhost,
            'rendered_vhost': rendered_vhost,
            'delete_url': delete_url,
            'listing_url': listing_url
        }
    )

pyvhost/apache_config/templates/apache_config/create.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<h1>Create Virtual Host</h1>
<form action="{% url 'apache_config:create' %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form create_form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Submit
    </button>
  {% endbuttons %}
</form>
{% endblock %}

pyvhost/apache_config/templates/apache_config/delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<h1>Delete {{ vhost.domain_name }}</h1>
<form action="{% url 'apache_config:delete' vhost_id=vhost.id %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form confirm_delete %}
  {% buttons %}
    <button type="submit" class="btn btn-danger">
      Delete
    </button>
  {% endbuttons %}
</form>
{% endblock %}

pyvhost/apache_config/templates/apache_config/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Apache Config</h1>
{% endblock %}

pyvhost/apache_config/templates/apache_config/list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<h1>Virtual Host List</h1>
{% bootstrap_button button_type='link' content='Create' href=create_url button_class='btn-primary' %}
<br /><br />
<div class="panel panel-default">
    <div class="panel-heading">Virtual Hosts</div>
    <table class="table">
        <thead>
            <tr>
                <th>Domain Name</th>
                <th>Include WWW</th>
                <th>Redirect to HTTPS</th>
                <th>PHP Enabled</th>
                <th>Use Let's Encrypt</th>
                <th>Active</th>
            </tr>
        </thead>
        <tbody>
        {% for vhost in vhost_list %}
            <tr class='clickable-row' data-href="{% url 'apache_config:show' vhost.id %}">
                <td>{{ vhost.domain_name }}</td>
                <td>{{ vhost.include_www }}</td>
                <td>{{ vhost.redirect_https }}</td>
                <td>{{ vhost.php_enabled }}</td>
                <td>{{ vhost.lets_encrypt }}</td>
                <td>{{ vhost.active }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

pyvhost/apache_config/templates/apache_config/show.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<h1>{{ vhost.domain_name }}</h1>
<p><b>Active: {{ vhost.active }}</b></p>
<p>Include WWW: {{ vhost.include_www }}</p>
<p>Redirect to HTTPs: {{ vhost.redirect_https }}</p>
<p>PHP Enabled: {{ vhost.php_enabled }}</p>
<p>Let's Encrypt Enabled: {{ vhost.lets_encrypt }}</p>
<br />
<textarea rows="10" cols="80">{{ rendered_vhost }}</textarea>
<br /><br />
{% bootstrap_button button_type='link' content='VHOST List' href=listing_url button_class='btn-primary' %}
{% bootstrap_button button_type='link' content='Delete' href=delete_url button_class='btn-danger' %}
{% endblock %}

pyvhost/pyvhost/templates/base.html
{% load bootstrap3 %}
<head>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script>
        jQuery(document).ready(function($) {
            $(".clickable-row").click(function() {
                window.location = $(this).data("href");
            });
        });
    </script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'apache_config:index' %}">PyVhost</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'apache_config:create' %}">Create</a></li>
                <li><a href="{% url 'apache_config:listing' %}">List</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Log Out</a></li>
            </ul>
        </div>
    </nav>
    {% bootstrap_messages %}
    <div class="container">
        <div class="col"></div>
        <div class="col-6">
            {% block content %}{% endblock %}
        </div>
        <div class="col"></div>
    </div>
</body>